---
title: "Final Project"
author: "Brayan Duran Medina"
output: html_document
---

```{r, cache=TRUE}
library(ggplot2)
library(dplyr)
library(countrycode)
```

```{r, cache=TRUE}
theme_HS<-list(theme(plot.title = element_text(lineheight=1, size=15, face="bold"), #set parameters of title
                     plot.subtitle = element_text(lineheight=1, size=12, face="bold"), # set parameters of subtitle
                     plot.caption = element_text(lineheight=1, size=13, hjust=1), # set parameters of caption
                     legend.title = element_blank (), # legend title (we don't want a title for the legens)
                     legend.text = element_text(colour="black", size = 15), # set parameters of legend text
                     legend.position="bottom", # set position of legend
                     # legend.justification=c(1,0), # set justification of legend
                     legend.background = element_rect(fill=NA, colour = NA), # set legend background
                     legend.key.size = unit(1.5, 'lines'), # set size of simbols of the legend
                     legend.key = element_rect(colour = NA, fill = NA), #set background of simbols in the legend
                     axis.title.x = element_blank (), # set x axis title (we don't want a title for the legend)
                     axis.text.x  = element_text(angle = 0,vjust=0.5, size=15,colour="black"), #set parameters of x axis text
                     axis.title.y = element_text(vjust=2, size=15,colour="black"), # set y axis title 
                     axis.text.y  = element_text(vjust=0.5, size=15,colour="black"), #set parameters of y axis text
                     strip.text = element_text(size=15, face="bold"), #text for facets
                     plot.background =  element_rect(fill = "white"), # set color of the background of the plot
                     panel.grid.major=element_line(colour="#E6E6E6",linewidth=.5), # set color of major grid lines
                     panel.grid.minor=element_line(colour="#E6E6E6",linewidth=.15), # set color of minor grid lines
                     panel.border = element_rect(colour = "#585858", fill=NA, linewidth=.75), #set color of panel border line
                     panel.background =element_rect(fill ="#FFFFFF", colour = "#FFFFFF"))) # set color of the background of the panel of the plot
```

```{r, cache=TRUE}
icpc_data <- read.csv("data/icpc-full.csv")

icpc_data$Year <- as.numeric(icpc_data$Year)

participation_summary <- icpc_data %>%
  group_by(Year) %>%
  summarize(
    num_countries = n_distinct(Country),
    num_teams = n_distinct(Team)
  )

head(participation_summary)
```

```{r, cache=TRUE}
plot <- ggplot(participation_summary, aes(x = Year, y = num_countries)) +
  geom_line(color = "steelblue", size = 1) +
  geom_point(color = "steelblue", size = 2) +
  annotate("rect", xmin = 2020, xmax = Inf, ymin = -Inf, ymax = Inf, alpha = 0.3, fill = "red") +
  annotate("text", x = 2020, y = 55, 
           label = "COVID-19\nPandemic", vjust = 1, hjust = -0.2, color = "red", size = 5, bold = TRUE) +
scale_x_continuous(breaks = seq(1999, 2023, by = 3), limits = c(1999, 2023)) +
  labs(
    title = "Growth in Number of Participating Countries from 1999 to present",
    x = "Year",
    y = "Number of Countries"
  ) +
  theme_HS

plot

ggsave("plot.png", plot, width = 10, height = 6, units = "in", dpi = 300)
```

```{r, cache=TRUE}
plot <- ggplot(participation_summary, aes(x = Year, y = num_teams)) +
  geom_line(color = "darkorange", size = 1) +
  geom_point(color = "darkorange", size = 2) +
  annotate("rect", xmin = 2020, xmax = Inf, ymin = -Inf, ymax = Inf, alpha = 0.3, fill = "red") +
  annotate("text", x = 2020, y = 150, 
           label = "COVID-19\nPandemic", vjust = 1, hjust = -0.2, color = "red", size = 5, bold = TRUE) +
  scale_x_continuous(breaks = seq(1999, 2023, by = 3), limits = c(1999, 2023)) +
  labs(
    title = "Growth in Number of Participating Teams from 1999 to present",
    x = "Year",
    y = "Number of Teams"
  ) +
  theme_HS

plot

ggsave("plot2.png", plot, width = 10, height = 6, units = "in", dpi = 300)
```

```{r, cache=TRUE}
icpc_data <- icpc_data %>%
  mutate(Gold = as.logical(Gold),
         Silver = as.logical(Silver),
         Bronze = as.logical(Bronze))


icpc_data <- icpc_data %>%
  mutate(Total_Medals = Gold + Silver + Bronze)

print(sum(icpc_data$Total_Medals))

university_medals <- icpc_data %>%
  group_by(University, Country) %>%
  summarize(Total_Medals = sum(Total_Medals, na.rm = TRUE)) %>%
  arrange(desc(Total_Medals)) %>%
  head(10) %>%
  mutate(University_Country = paste(University, " (", Country, ")", sep = ""))

country_medals <- icpc_data %>%
  group_by(Country) %>%
  summarize(Total_Medals = sum(Total_Medals, na.rm = TRUE)) %>%
  arrange(desc(Total_Medals)) %>%
  head(10)

print(university_medals)
print(country_medals)

icpc_data <- icpc_data %>%
  mutate(Region = countrycode(Country, "country.name", "region"),
         Continent = countrycode(Country, "country.name", "continent"))

south_america_regions <- c("Latin America & Caribbean")
north_america_regions <- c("North America")

head(icpc_data)

print(unique(icpc_data$Region))

icpc_data <- icpc_data %>%
  mutate(Continent = case_when(
    Region %in% south_america_regions ~ "South America",
    Region %in% north_america_regions ~ "North America",
    TRUE ~ Continent
  ))

continent_medals <- icpc_data %>%
  group_by(Continent) %>%
  summarize(Total_Medals = sum(Total_Medals, na.rm = TRUE)) %>%
  arrange(desc(Total_Medals))
```

```{r, cache=TRUE}
plot <- ggplot(university_medals, aes(x = reorder(University_Country, Total_Medals), y = Total_Medals)) +
  geom_bar(stat = "identity", fill = "purple") +
  coord_flip() +
  scale_y_continuous(breaks = seq(0, 16, by = 2)) +
  labs(
    title = "Top 10 Universities with Most Medals",
    y = "Total Medals",
    x = NULL
  ) +
    theme_HS

plot

ggsave("plot3.png", plot, width = 12, height = 6, units = "in", dpi = 300)
```

```{r, cache=TRUE}
print(max(country_medals$Total_Medals))
plot <- ggplot(country_medals, aes(x = reorder(Country, Total_Medals), y = Total_Medals)) +
  geom_bar(stat = "identity", fill = "darkorange") +
  scale_y_continuous(breaks = seq(0, 87, by = 5)) +
  coord_flip() +
  labs(
    title = "Top 10 Countries with Most Medals",
    y = "Total Medals",
    x = NULL
  ) +
    theme_HS

plot

ggsave("plot4.png", plot, width = 12, height = 6, units = "in", dpi = 300)
```

```{r, cache=TRUE}
print(max(continent_medals$Total_Medals))
plot <- ggplot(continent_medals, aes(x = reorder(Continent, Total_Medals), y = Total_Medals)) +
  geom_bar(stat = "identity", fill = "forestgreen") +
  coord_flip() +
  scale_y_continuous(breaks = seq(0, 156, by = 12)) + 
  labs(
    title = "Total Medals by Continent",
    x = NULL,
    y = "Total Medals"
  ) +
  theme_HS

plot

ggsave("plot5.png", plot, width = 12, height = 6, units = "in", dpi = 300)

total_medals <- sum(continent_medals$Total_Medals)

print(total_medals)
```

```{r, cache=TRUE}
library(broom)
library(tidyr)

icpc_data <- read.csv("data/icpc-full.csv")

icpc_data <- icpc_data %>%
  mutate(Gold = as.logical(Gold),
         Silver = as.logical(Silver),
         Bronze = as.logical(Bronze))

icpc_data <- icpc_data %>%
  mutate(Total_Medals = Gold + Silver + Bronze)

country_year_medals <- icpc_data %>%
  group_by(Country, Year) %>%
  summarize(Total_Medals = sum(Total_Medals, na.rm = TRUE)) %>%
  ungroup()

all_years <- seq(min(country_year_medals$Year), max(country_year_medals$Year))
all_countries <- unique(country_year_medals$Country)

all_combinations <- expand.grid(Country = all_countries, Year = all_years)

country_year_medals_complete <- all_combinations %>%
  left_join(country_year_medals, by = c("Country", "Year")) %>%
  mutate(Total_Medals = ifelse(is.na(Total_Medals), 0, Total_Medals))

get_slope <- function(data) {
  model <- lm(Total_Medals ~ Year, data = data)
  slope <- coef(model)["Year"]
  return(slope)
}

country_slopes <- country_year_medals_complete %>%
  group_by(Country) %>%
  summarize(Slope = get_slope(cur_data_all())) %>%
  arrange(desc(Slope))

top_4_countries <- country_slopes %>%
  top_n(4, Slope) %>%
  pull(Country)

top_4_countries_data <- country_year_medals_complete %>%
  filter(Country %in% top_4_countries)

top_4_countries_data$Country <- factor(top_4_countries_data$Country, levels = top_4_countries)


facet_plot <- ggplot(top_4_countries_data, aes(x = Year, y = Total_Medals)) +
  geom_line() +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  scale_y_continuous(breaks = seq(0, 2, by = 1), limits = c(0, 2)) +
  scale_x_continuous(breaks = seq(1999, 2023, by = 4), limits = c(1999, 2023)) +
  facet_wrap(~ Country, scales = "free_y") +
  labs(
    title = "Medals Over Years for Top 4 Countries with Highest Slopes",
    x = NULL,
    y = "Total Medals"
  ) + theme_HS

top_10_countries <- country_slopes %>%
  top_n(10, Slope)

bar_plot <- ggplot(top_10_countries, aes(x = reorder(Country, Slope), y = Slope)) +
  geom_bar(stat = "identity", fill = "dodgerblue") +
  coord_flip() +
  scale_y_continuous(breaks = seq(0, 0.4, by = 0.01)) +
  labs(
    title = "Top 10 Countries by Linear Regression Slope",
    subtitle = "Indicating the Performance Trend Over Years",
    x = NULL,
    y = "Slope (Performance Trend)"
  ) + theme_HS

facet_plot
bar_plot

ggsave("plot7.png", facet_plot, width = 12, height = 8, units = "in", dpi = 300)
ggsave("plot6.png", bar_plot, width = 12, height = 8, units = "in", dpi = 300)
```

```{r, cache=TRUE}
icpc_data <- read.csv("data/icpc-full.csv")

head(icpc_data)

total_teams_per_year <- icpc_data %>%
  group_by(Year) %>%
  summarize(Total_Teams_Year = n())

ranking_data <- icpc_data %>%
  group_by(Country, Year) %>%
  summarize(Average_Rank = ifelse(all(is.na(Rank)), NA, mean(Rank, na.rm = TRUE))) %>%
  ungroup()

ranking_data <- ranking_data %>%
  left_join(total_teams_per_year, by = "Year")

ranking_data <- ranking_data %>%
  mutate(Average_Rank = ifelse(is.na(Average_Rank), Total_Teams_Year, Average_Rank))

print(ranking_data)

ranking_data <- ranking_data %>%
  mutate(Scaled_Rank = (Average_Rank / Total_Teams_Year) * 100)

all_years <- seq(min(ranking_data$Year), max(ranking_data$Year))
all_countries <- unique(ranking_data$Country)

all_combinations <- expand.grid(Country = all_countries, Year = all_years)

ranking_data_complete <- all_combinations %>%
  left_join(ranking_data, by = c("Country", "Year")) %>%
  mutate(Scaled_Rank = ifelse(is.na(Scaled_Rank), 100, Scaled_Rank))

get_slope <- function(data) {
  model <- lm(Scaled_Rank ~ Year, data = data)
  slope <- coef(model)["Year"]
  return(slope)
}

country_slopes <- ranking_data_complete %>%
  group_by(Country) %>%
  summarize(Slope = get_slope(cur_data_all())) %>%
  arrange(Slope)

print(country_slopes)

top_10_countries <- country_slopes %>%
  top_n(10, -Slope)

top_4_countries <- country_slopes %>%
  top_n(4, -Slope) %>%
  pull(Country)

top_4_countries_data <- ranking_data_complete %>%
  filter(Country %in% top_4_countries)

top_4_countries_data$Country <- factor(top_4_countries_data$Country, levels = top_4_countries)

print(top_10_countries)

print(top_4_countries_data)

facet_plot <- ggplot(top_4_countries_data, aes(x = Year, y = Scaled_Rank)) +
  geom_line() +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  scale_y_continuous(breaks = seq(0, 100, by = 25), limits = c(0, 100)) +
  scale_x_continuous(breaks = seq(1999, 2023, by = 4), limits = c(1999, 2023)) +
  facet_wrap(~ Country, scales = "free_y") +
  labs(
    title = "Average Ranking (%) Over Years for Top 4 Countries with Lowest Slopes",
    x = NULL,
    y = "Scaled Rank"
  ) + theme_HS

bar_plot <- ggplot(top_10_countries, aes(x = reorder(Country, -Slope), y = Slope)) +
  geom_bar(stat = "identity", fill = "brown") +
  coord_flip() +
  labs(
    title = "Top 10 Countries by Linear Regression Slope",
    subtitle = "Indicating the Performance Trend Over Years",
    x = NULL,
    y = "Slope (Performance Trend)"
  ) + theme_HS

facet_plot
bar_plot

ggsave("plot9.png", facet_plot, width = 12, height = 8, units = "in", dpi = 300)
ggsave("plot8.png", bar_plot, width = 12, height = 8, units = "in", dpi = 300)

cuba_data <- ranking_data_complete %>%
  filter(Country == "Cuba")

cuba_plot <- ggplot(cuba_data, aes(x = Year, y = Scaled_Rank)) +
  geom_line() +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  scale_y_continuous(breaks = seq(0, 100, by = 25), limits = c(0, 100)) +
  scale_x_continuous(breaks = seq(1999, 2023, by = 4), limits = c(1999, 2023)) +
  labs(
    title = "Average Ranking (%) Over Years for Cuba",
    x = NULL,
    y = "Scaled Rank"
  ) + theme_HS

cuba_plot

ggsave("plot10.png", cuba_plot, width = 12, height = 6, units = "in", dpi = 300)
```

```{r}
library(leaflet)
library(dplyr)
library(readr)
library(htmltools)
library(sf)

world <- st_read("data/world.shp")
data <- read_csv("data/icpc-full.csv")

data$Host[data$Host == "Czechia"] <- "Czech Rep."
data$Country[data$Country == "Czechia"] <- "Czech Rep."

host_counts <- data %>%
  select(Year, Host) %>%
  distinct() %>%
  group_by(Host) %>%
  summarise(Count = n()) %>%
  ungroup()

total_teams_per_year <- icpc_data %>%
  group_by(Year) %>%
  summarize(Total_Teams_Year = n())

ranking_data <- icpc_data %>%
  group_by(Country, Year) %>%
  summarize(Average_Rank = ifelse(all(is.na(Rank)), NA, mean(Rank, na.rm = TRUE))) %>%
  ungroup()

ranking_data <- ranking_data %>%
  left_join(total_teams_per_year, by = "Year")

ranking_data <- ranking_data %>%
  mutate(Average_Rank = ifelse(is.na(Average_Rank), Total_Teams_Year, Average_Rank))

print(ranking_data)

ranking_data <- ranking_data %>%
  mutate(Scaled_Rank = (Average_Rank / Total_Teams_Year) * 100)

all_years <- seq(min(ranking_data$Year), max(ranking_data$Year))
all_countries <- unique(ranking_data$Country)

all_combinations <- expand.grid(Country = all_countries, Year = all_years)

ranking_data_complete <- all_combinations %>%
  left_join(ranking_data, by = c("Country", "Year")) %>%
  mutate(Scaled_Rank = ifelse(is.na(Scaled_Rank), 100, Scaled_Rank))

average_ranking <- ranking_data_complete %>%
  group_by(Country) %>%
  summarize(Average_Rank = mean(Scaled_Rank, na.rm = TRUE)) %>%
  arrange(Average_Rank)

world <- world %>%
  left_join(host_counts, by = c("name" = "Host")) %>%
  left_join(average_ranking, by = c("name" = "Country"))

world$Average_Rank[is.na(world$Average_Rank)] <- 100

world$Count[is.na(world$Count)] <- 0

pal_host <- colorNumeric("YlOrRd", domain = world$Count)

pal_rank <- colorNumeric("YlGnBu", domain = world$Average_Rank, reverse = TRUE)

total_hosted <- sum(world$Count)

correlation <- cor(world$Count, world$Average_Rank, use = "complete.obs")

print(correlation)
```

## International Collegiate Programming Contest (ICPC) Heatmap of Host Countries

```{r}
map_host <- leaflet(data = world, options = leafletOptions(
  dragging = FALSE,
  touchZoom = FALSE,
  doubleClickZoom = FALSE,
  scrollWheelZoom = FALSE,
  boxZoom = FALSE,
  keyboard = FALSE,
  zoomControl = FALSE,
  tap = FALSE
)) %>%
  addTiles() %>%
  setView(lng = 30, lat = 40, zoom = 1.1) %>%
  addPolygons(
    fillColor = ~pal_host(Count),
    weight = 1,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 3,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE
    ),
    label = ~paste(name, ": ", Count, " times hosted"),
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"
    )
  ) %>%
  addLegend(
    pal = pal_host,
    values = ~Count,
    opacity = 0.7,
    title = "Times Hosted",
    position = "bottomright"
  )

map_host
```

## International Collegiate Programming Contest (ICPC) Heatmap of Ranking Average

```{r}
map_rank <- leaflet(data = world, options = leafletOptions(
  dragging = FALSE,
  touchZoom = FALSE,
  doubleClickZoom = FALSE,
  scrollWheelZoom = FALSE,
  boxZoom = FALSE,
  keyboard = FALSE,
  zoomControl = FALSE,
  tap = FALSE
)) %>%
  addTiles() %>%
  setView(lng = 30, lat = 40, zoom = 1.1) %>%
  addPolygons(
    fillColor = ~pal_rank(Average_Rank),
    weight = 1,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 3,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE
    ),
    label = ~ifelse(is.na(Average_Rank), paste(name, ": No Participation"), paste(name, ": Average Rank ", round(Average_Rank, 2))),
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"
    )
  ) %>%
  addLegend(
    pal = pal_rank,
    values = ~Average_Rank,
    opacity = 0.7,
    title = "Average Rank (%)",
    position = "bottomright"
  )

map_rank
```